name: check-deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: |
          chmod +x scripts/build.sh
          chmod +x scripts/deploy.sh
          scripts/build.sh
      - name: Test
        run: |
          cd ~/work/zesty-sdk/zesty-sdk
          yarn run test
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: |
          scripts/build.sh
      - name: Deploy
        run: |
          scripts/deploy.sh
