name: check-deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: |
          scripts/build.sh
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: |
          scripts/test.sh
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - run: |
        scripts/deploy.sh
