name: check-deploy

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: |
          chmod +x scripts/build.sh
          chmod +x scripts/deploy.sh
          scripts/build.sh
      - name: Test
        run: |
          cd ~/work/billboard/billboard
          npx playwright install
          yarn run test
  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: ${{ always() && (contains(needs.test.result, 'success') || contains(github.event.head_commit.message, '[test skip]')) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: |
          chmod +x scripts/build.sh
          chmod +x scripts/deploy.sh
          scripts/build.sh
      - name: Deploy
        run: |
          scripts/deploy.sh